apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: game-2048
  namespace: default
spec:
  replicas: 3

  selector:
    matchLabels:
      app: 2048-game

  template:
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
        - name: game-2048
          image: nginx:latest
          ports:
            - containerPort: 80

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 100
